# Generated by Django 5.0.3 on 2024-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bird_age_bird_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bird',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
